ListDemo2.iterateList();

List<integer> tempList = new list<integer>{5,21,15,99,77,101};

integer sum1= ListDemo2.add(tempList);
system.debug('sum is '+sum1);


list<string> ls = new list<string>{'list','set', 'map', 'array'};
ls.add('methods');
ls.add('constructor');
ListDemo2.iterateListString(ls);

List<string> strg = new List<string>{'apple', 'pear', 'orange', 'melon', 'mango'};
ListDemo2.add(strg);

ListDemo2.iterateListString99();