public class ContactTriggerHandler {
    // public static void validateContactUpdate1(List<Contact> cTriggerNew,List<Contact> cTriggerOld, Map<Id,Contact> cTriggerNewMap, Map<Id,Contact> cTriggerOldMap) {
        
    //     for (Contact eachContact : cTriggerNew) {
    //         Contact oldContact = cTriggerOldMap.get(eachContact.Id);

    //         if (oldContact.LeadSource=='Partner Referral') {
    //             eachContact.addError('Cannot update contact with lead source as Partner Referral');
    //         }
            
    //     }
    // }
    // public static void validateContactUpdate2(List<Contact> cTriggerNew,List<Contact> cTriggerOld, Map<Id,Contact> cTriggerNewMap, Map<Id,Contact> cTriggerOldMap) {

    //     for (Contact eachNewContact : cTriggerNew) {
    //         if (eachNewContact.LeadSource!=cTriggerOldMap.get(eachNewContact.id).LeadSource) {
    //             eachNewContact.LeadSource.addError('Cannot update leadsource. Please user!.Go away');
    //         }
    //     }
    // }
    
 }
