public with sharing class ArthimaticCalculations {
   public integer Addition(integer x, integer y){
        integer z= x+y;
        return z;
   }
   public integer Subtraction(integer x,integer y){
        integer z = x-y;
        return z;
   }
   public integer Multiplication(Integer x, integer y, integer w){
        integer z = x*y*w;
        return z;
   }
   public string concatString(string a , string b){
    string z= a+' & '+b;
    return z;
   }
}